FROM python:3.7-slim
# Tell python not to produce any `__pycache__` and `*.pyc` files
ENV PYTHONBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 INSIDE_DOCKER=1 POETRY_VERSION=1.0.5 POETRY_VIRTUALENVS_CREATE=true

# Install all dependencies needed to install our python requirements
# Install build dependencies
RUN apt update \
	&& apt install -y gettext

# Set the correct timezone
RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && echo "Europe/Berlin" > /etc/timezone

RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

# Copy Pipfile, install pipenv and then install all python dependencies
COPY pyproject.toml poetry.lock /

RUN PATH="$PATH:$HOME/.poetry/bin" && poetry install

# Copy the entrypoint.sh and start.sh and make them executable
COPY docker/local/entrypoint.sh docker/local/start.sh /
RUN chmod +x /entrypoint.sh /start.sh

# All subsequent commands will be run from the /app folder
WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
